require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'config/spring.rb'
    - 'tmp/**/*'
    - 'lib/deploy.rb'
    - 'Dockerfile.*'
  NewCops: enable
  TargetRubyVersion: 2.7
Layout/ClassStructure:
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - public_class_methods
    - initializer
    - instance_methods
    - protected_methods
    - private_methods
Layout/LineLength:
  Max: 120
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/UnreachableCode:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Rails/EnvironmentVariableAccess:
  AllowReads: true
Naming/FileName:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: 'arguments'
RSpec/ExampleLength:
  Max: 20
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ImplicitExpect:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/PredicateMatcher:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/VariableName:
  Enabled: true
  IgnoredPatterns:
    - 'Authorization'
Style/ClassAndModuleChildren:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/SignalException:
  Enabled: false
