version: '3.9'

volumes:
  postgres_data: {}
  bundle: {}
  npm: {}

networks:
  challenge-net:
    driver: bridge

services:
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - '5433:5432'
    networks:
      - challenge-net

  challenge: &rails
    tty: true
    stdin_open: true
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - 'POSTGRES_HOST=db'
    volumes:
      - '.:/app:delegated'
      - '~/.ssh:/root/.ssh:delegated'
      - 'bundle:/usr/local/bundle'
      - 'npm:/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - challenge-net